version: '3.8'

services:
  rsync:
    build: .
    ports:
      - "873:873"
    volumes:
      - /absolute/path/to/storage:/data
    environment:
      - RSYNC_USER=${RSYNC_USER}
      - RSYNC_PASSWORD=${RSYNC_PASSWORD}
    restart: unless-stopped